const Menu = [
    {
        id: 1,
        category: "Movies",
        image: "img/poster/ucm_poster01.jpg",
        title: "Самбараас бөмбөг авах",
        date: "2022",
        quality: "hd",
        duration: "7 min",
        ratings: "3.5",
    },
    {
        id: 2,
        category: "Movies",
        image: "img/poster/ucm_poster02.jpg",
        title: "Холын зайн шидэлт",
        date: "2022",
        quality: "hd",
        duration: "12 min",
        ratings: "3.5",
    },
    {
        id: 3,
        category: "Movies",
        image: "img/poster/ucm_poster03.jpg",
        title: "Довтолгоо",
        date: "2021",
        quality: "4k",
        duration: "8 min",
        ratings: "3.0",
    },
    {
        id: 4,
        category: "Movies",
        image: "img/poster/ucm_poster04.jpg",
        title: "Бөмбөг эзэмшилт",
        date: "2021",
        quality: "4k",
        duration: "11 min",
        ratings: "3.6",
    },
    {
        id: 5,
        category: "Movies",
        image: "img/poster/ucm_poster01.jpg",
        title: "Самбараас бөмбөг авах",
        date: "2022",
        quality: "hd",
        duration: "7 min",
        ratings: "3.5",

    },
    {
        id: 6,
        category: "Movies",
        image: "img/poster/ucm_poster02.jpg",
        title: "Холын зайн шидэлт",
        date: "2022",
        quality: "hd",
        duration: "12 min",
        ratings: "3.5",
    },
    {
        id: 7,
        category: "Movies",
        image: "img/poster/ucm_poster03.jpg",
        title: "Довтолгоо",
        date: "2021",
        quality: "4k",
        duration: "8 min",
        ratings: "3.0",
    },
    {
        id: 8,
        category: "Movies",
        image: "img/poster/ucm_poster04.jpg",
        title: "Бөмбөг эзэмшилт",
        date: "2021",
        quality: "4k",
        duration: "11 min",
        ratings: "3.6",
    }, {
        id: 9,
        category: "Movies",
        image: "img/poster/ucm_poster01.jpg",
        title: "Самбараас бөмбөг авах",
        date: "2022",
        quality: "hd",
        duration: "7 min",
        ratings: "3.5",

    },
    {
        id: 10,
        category: "Movies",
        image: "img/poster/ucm_poster02.jpg",
        title: "Холын зайн шидэлт",
        date: "2022",
        quality: "hd",
        duration: "12 min",
        ratings: "3.5",
    },
    {
        id: 11,
        category: "Movies",
        image: "img/poster/ucm_poster03.jpg",
        title: "Довтолгоо",
        date: "2021",
        quality: "4k",
        duration: "8 min",
        ratings: "3.0",
    },
    {
        id: 12,
        category: "Movies",
        image: "img/poster/ucm_poster04.jpg",
        title: "Бөмбөг эзэмшилт",
        date: "2021",
        quality: "4k",
        duration: "11 min",
        ratings: "3.6",
    },




]
export default Menu;